### ISSUE TITLE
Frame_Score.png has a typo

### ISSUE THREAD

**Issue by Yuberz** [MoshirMoshir/Moshir-OpenTaiko-Skin#1]
in Graphics > 3_SongSelect, Frame_Score.png has a typo.
Instead of "Normal" it says "Noraml"

![Frame_Score](https://github.com/MoshirMoshir/Moshir-OpenTaiko-Skin/assets/40701826/0e906d8e-eda7-4fdc-8192-ff8e53fd2a3e)

**Comment by MoshirMoshir** [comment]
Thanks! It should be fixed now. I'll post a hotfix release as well once I confirm it's fixed.
