### ISSUE TITLE
Frame_Score.png says Noraml

### ISSUE THREAD

**Issue by MaoMaster69** [MoshirMoshir/Moshir-OpenTaiko-Skin#2]
When selecting a song, the difficulities mispell "Normal"

That's all!!
I'd leave an image, as well as the image file where I fixed it, but the power went out recently and the internet's not back. Just LTE data (ugh).

For anyone who's wanting to fix it themselves, the 
.kra file is included in Graphics/3_SongSelect/Frame_Score.kra
you'll need Krita. (Open Source, Free, robust illustration program)

**Comment by MoshirMoshir** [comment]
I thought I had fixed this, but I guess I didn't, finally did though XD
